import { PRINT_JOB_STATUS, type PrintJobStatus } from "./printJob.status.js";

export const PRINT_JOB_TRANSITIONS: Record<
  PrintJobStatus,
  readonly PrintJobStatus[]
> = {
  [PRINT_JOB_STATUS.CREATED]: [
    PRINT_JOB_STATUS.PROCESSING,
    PRINT_JOB_STATUS.CANCELLED,
  ],

  [PRINT_JOB_STATUS.PROCESSING]: [
    PRINT_JOB_STATUS.PAYMENT_REQUIRED,
    PRINT_JOB_STATUS.PROCESSING_FAILED,
    PRINT_JOB_STATUS.CANCELLED,
  ],

  [PRINT_JOB_STATUS.PAYMENT_REQUIRED]: [
    PRINT_JOB_STATUS.QUEUED,
    PRINT_JOB_STATUS.CANCELLED,
  ],

  [PRINT_JOB_STATUS.QUEUED]: [
    PRINT_JOB_STATUS.DISPATCHED,
    PRINT_JOB_STATUS.CANCELLED,
  ],

  [PRINT_JOB_STATUS.DISPATCHED]: [
    PRINT_JOB_STATUS.PRINTING,
    PRINT_JOB_STATUS.PRINT_FAILED,
  ],

  [PRINT_JOB_STATUS.PRINTING]: [
    PRINT_JOB_STATUS.COMPLETED,
    PRINT_JOB_STATUS.PRINT_FAILED,
  ],

  [PRINT_JOB_STATUS.COMPLETED]: [],

  [PRINT_JOB_STATUS.PROCESSING_FAILED]: [
    PRINT_JOB_STATUS.PROCESSING,
    PRINT_JOB_STATUS.CANCELLED,
  ],

  [PRINT_JOB_STATUS.PRINT_FAILED]: [
    PRINT_JOB_STATUS.QUEUED,
    PRINT_JOB_STATUS.CANCELLED,
  ],

  [PRINT_JOB_STATUS.CANCELLED]: [],
};
