export const PRINT_JOB_STATUS = {
  CREATED: "CREATED",

  PROCESSING: "PROCESSING",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  QUEUED: "QUEUED",
  DISPATCHED: "DISPATCHED",
  PRINTING: "PRINTING",
  COMPLETED: "COMPLETED",

  PROCESSING_FAILED: "PROCESSING_FAILED",
  PRINT_FAILED: "PRINT_FAILED",
  CANCELLED: "CANCELLED",
} as const;

export type PrintJobStatus =
  (typeof PRINT_JOB_STATUS)[keyof typeof PRINT_JOB_STATUS];
